import {
  Globe,
  LayoutDashboard,
  MessageSquare,
  Award,
  Building2,
  TrendingUp,
} from "lucide-react"

export const PILLARS = [
  {
    id: "attract",
    label: "Attract",
    heading: "Attract Qualified Enquiries",
    summary: "Bring qualified traffic to your business.",
    icon: Globe,
    problem: "Most trades rely on referrals and inconsistent lead flow.",
    outcome: "A predictable inbound enquiry engine.",
    services: [
      { title: "Conversion Website System", description: "High-converting, mobile-first website built to generate consistent enquiries." },
      { title: "Local SEO & Visibility Setup", description: "Optimised site structure, service pages and local targeting for Google visibility." },
      { title: "Ongoing SEO & Content Expansion", description: "Monthly service pages, location pages and content to grow long-term search presence." },
    ],
  },
  {
    id: "capture",
    label: "Capture",
    heading: "Capture Every Enquiry",
    summary: "Turn visitors into trackable enquiries.",
    icon: LayoutDashboard,
    problem: "Leads slip through the cracks without a central place to track them.",
    outcome: "Every enquiry captured, tracked and actionable.",
    services: [
      { title: "CRM & Pipeline System", description: "Custom lead tracking for enquiries, quotes and closed jobs in one place." },
      { title: "Instant Lead Alert System", description: "SMS and email notifications the moment new enquiries are submitted." },
      { title: "Booking & Appointment System", description: "Integrated calendar with confirmations and reminders to reduce no-shows." },
    ],
  },
  {
    id: "convert",
    label: "Convert",
    heading: "Convert Quotes Into Contracts",
    summary: "Automate follow-up and increase close rate.",
    icon: MessageSquare,
    problem: "Slow or missed follow-up means lost quotes and forgotten leads.",
    outcome: "Higher quote acceptance and reactivated past customers.",
    services: [
      { title: "Quote Follow-Up Automation", description: "Automated reminders and follow-up to increase quote acceptance." },
      { title: "Customer Reactivation Campaigns", description: "Targeted SMS and email to generate new work from past customers." },
      { title: "Review & Reputation Growth System", description: "Automated review requests and reputation management for trust and rankings." },
    ],
  },
  {
    id: "authority",
    label: "Authority",
    heading: "Build Authority & Trust",
    summary: "Build trust and professional positioning.",
    icon: Award,
    problem: "Competitors with weaker work win because they look more credible.",
    outcome: "Trust and credibility that wins before you quote.",
    services: [
      { title: "Social Authority Pack", description: "Branded social templates and content to strengthen online credibility." },
      { title: "Capability & Authority Build", description: "Website sections for accreditations, insurance, compliance and case studies." },
      { title: "Company Profile & Documentation Pack", description: "Capability statement and tender-ready documentation templates." },
    ],
  },
  {
    id: "contract-growth",
    label: "Contract Growth",
    heading: "Contract Growth",
    summary: "Structure your business to win tenders.",
    icon: Building2,
    problem: "Commercial and council opportunities are missed without the right structure.",
    outcome: "Contract-ready positioning and tender pipeline visibility.",
    services: [
      { title: "Tender-Ready Digital Infrastructure", description: "Website and docs structured for commercial and council contract applications." },
      { title: "Contract Opportunity Monitoring", description: "Ongoing monitoring of relevant tenders delivered to you." },
      { title: "Tender Tracking CRM", description: "Pipeline for contract opportunities, submissions and follow-ups." },
    ],
  },
  {
    id: "growth-management",
    label: "Scale",
    heading: "Scale & Optimise",
    summary: "Optimise and expand over time.",
    icon: TrendingUp,
    problem: "Without clear metrics and ongoing optimisation, growth plateaus.",
    outcome: "Continuous optimisation and scaling that compounds.",
    services: [
      { title: "Automation & Workflow Setup", description: "Custom automation for enquiries, follow-ups and internal processes." },
      { title: "Performance Dashboard & Reporting", description: "Reporting on leads, pipeline value, conversion rates and growth." },
      { title: "Ongoing Growth Management", description: "Continuous optimisation of systems and digital presence for scaling." },
    ],
  },
] as const
